# Amount of levels required to make an item infinite
infinite-cost: 30

#Text to display when anvil usage is denied
#use '&' to change the colour of the message
anvil-message: &cYou do not have the required permissions to do this action

#List of foods that are unable to be made infinite
#add more foods to the list by pressing space then -
#example:
# - ENCHANTED_GOLDEN_APPLE
# - COOKED_BEEF
banned-foods: